### Exploração dos dados Parquet
Vamos ler os arquivos Parquet da camada Bronze e fazer consultas iniciais.

In [1]:
import duckdb
import pandas as pd

In [ ]:
con = duckdb.connect()

In [24]:
base_path = '../data/lake/silver/'

# Ler um parquet
parquet_file = base_path + 'br_bndes_operacoes.parquet'
df = con.execute(f"SELECT * FROM '{parquet_file}' LIMIT 5").fetchdf()
df.head()

,razao_social_cliente,cnpj_cliente,descricao_projeto,sigla_uf,nome_municipio,id_municipio,id_contrato,data_contratacao,valor_contratado,valor_desembolsado,...,cnpj_instituicao_financeira_credenciada,tipo_garantia,tipo_excepcionalidade,situacao_contrato,secao_cnae,divisao_cnae,grupo_cnae,classe_cnae,subclasse_cnae,data_apuracao
0,COPACOL-COOPERATIVA AGROINDUSTRIAL CONSOLATA,76093731000190,INVESTIMENTOS EM AMPLIACAO DA CAPACIDADE DE RE...,PR,SEM MUNICÍPIO,<NA>,09203361,2009-06-30,35900000.0,35900000.0,...,92816560000137,DEFINIDA PELO AGENTE FINANCEIRO,None,LIQUIDADO,C,10,101,10121,1012101,2026-06-04
1,LAR COOPERATIVA AGROINDUSTRIAL,77752293000198,DIRETA - AMPLICACAO DE LINHA DE ABATE DE FRANG...,PR,MATELANDIA,4115606,09203571,2009-06-29,66998000.0,66998000.0,...,NaN,REAL,None,LIQUIDADO,C,10,101,10121,1012101,2026-06-04
2,LAR COOPERATIVA AGROINDUSTRIAL,77752293000198,DIRETA - AMPLICACAO DE LINHA DE ABATE DE FRANG...,MS,SEM MUNICÍPIO,<NA>,09203581,2009-06-30,20897000.0,20897000.0,...,92816560000137,DEFINIDA PELO AGENTE FINANCEIRO,None,LIQUIDADO,C,10,101,10121,1012101,2026-06-04
3,COCARI - COOPERATIVA AGROPECUARIA E INDUSTRIAL,78956968000183,SUPLEMENTACAO DE RECURSOS A IMPLANTACAO DE UM ...,PR,MANDAGUARI,4114203,09204441,2009-06-30,37000000.0,37000000.0,...,92816560000137,DEFINIDA PELO AGENTE FINANCEIRO,None,LIQUIDADO,C,10,101,10121,1012101,2026-06-04
4,COCARI - COOPERATIVA AGROPECUARIA E INDUSTRIAL,78956968000183,SUPLEMENTACAO DE RECURSOS A IMPLANTACAO DE UM ...,PR,MANDAGUARI,4114203,09204451,2009-10-09,50000000.0,50000000.0,...,92816560000137,DEFINIDA PELO AGENTE FINANCEIRO,None,LIQUIDADO,C,10,101,10121,1012101,2026-06-04

In [ ]:
# Mostrar colunas do parquet
schema = con.execute(f"DESCRIBE SELECT * FROM '{parquet_file}'").fetchdf()
schema

,column_name,column_type,null,key,default,extra
0,razao_social_cliente,VARCHAR,YES,None,None,None
1,cnpj_cliente,VARCHAR,YES,None,None,None
2,descricao_projeto,VARCHAR,YES,None,None,None
3,sigla_uf,VARCHAR,YES,None,None,None
4,nome_municipio,VARCHAR,YES,None,None,None
5,id_municipio,BIGINT,YES,None,None,None
6,id_contrato,VARCHAR,YES,None,None,None
7,data_contratacao,DATE,YES,None,None,None
8,valor_contratado,DOUBLE,YES,None,None,None
9,valor_desembolsado,DOUBLE,YES,None,None,None
10,tipo_fonte_recursos,VARCHAR,YES,None,None,None
11,custo_financeiro,VARCHAR,YES,None,None,None
12,taxa_juros,DOUBLE,YES,None,None,None
13,prazo_carencia,BIGINT,YES,None,None,None
14,prazo_amortizacao,BIGINT,YES,None,None,None
15,modalidade_apoio,VARCHAR,YES,None,None,None
16,forma_apoio,VARCHAR,YES,None,None,None
17,produto,VARCHAR,YES,None,None,None
18,tipo_instrumento_financeiro,VARCHAR,YES,None,None,None
19,indicador_inovacao,BIGINT,YES,None,None,None
20,area_operacional_bndes,VARCHAR,YES,None,None,None
21,setor_cnae_bndes,VARCHAR,YES,None,None,None
22,subsetor_agrupado_cnae_bndes,VARCHAR,YES,None,None,None
23,descricao_subclasse,VARCHAR,YES,None,None,None
24,setor_bndes,VARCHAR,YES,None,None,None
25,subsetor_bndes,VARCHAR,YES,None,None,None
26,porte_cliente,VARCHAR,YES,None,None,None
27,natureza_cliente,VARCHAR,YES,None,None,None
28,nome_instituicao_financeira_credenciada,VARCHAR,YES,None,None,None
29,cnpj_instituicao_financeira_credenciada,VARCHAR,YES,None,None,None
30,tipo_garantia,VARCHAR,YES,None,None,None
31,tipo_excepcionalidade,VARCHAR,YES,None,None,None
32,situacao_contrato,VARCHAR,YES,None,None,None
33,secao_cnae,VARCHAR,YES,None,None,None
34,divisao_cnae,VARCHAR,YES,None,None,None
35,grupo_cnae,VARCHAR,YES,None,None,None
36,classe_cnae,VARCHAR,YES,None,None,None
37,subclasse_cnae,VARCHAR,YES,None,None,None
38,data_apuracao,DATE,YES,None,None,None

In [31]:
# Consultas iniciais

# Quantidade de linhas
total_linhas = con.execute(f"SELECT COUNT(*) AS total_linhas FROM '{parquet_file}'").fetchdf()
total_linhas

   total_linhas
0         23483

### Consulta Diretorios CNAE

In [ ]:
base_path = '../lake/silver/'

# Ler um parquet
parquet_file = base_path + 'br_bd_diretorios_brasil_cnae_2.parquet'
df = con.execute(f"SELECT * FROM '{parquet_file}' LIMIT 5").fetchdf()
df.head()

,subclasse,descricao_subclasse,classe,descricao_classe,grupo,descricao_grupo,divisao,descricao_divisao,secao,descricao_secao,indicador_cnae_2_0,indicador_cnae_2_1,indicador_cnae_2_2,indicador_cnae_2_3
0,9700500,Serviços domésticos,97005,Serviços domésticos,970,Serviços domésticos,97,Serviços Domésticos,T,Serviços Domésticos,1,1,1,1
1,9900800,Organismos internacionais e outras instituiçõe...,99008,Organismos internacionais e outras instituiçõe...,990,Organismos internacionais e outras instituiçõe...,99,Organismos Internacionais E Outras Instituiçõe...,U,Organismos Internacionais E Outras Instituiçõe...,1,1,1,0
2,0111301,Cultivo de arroz,01113,Cultivo de cereais,011,Produção de lavouras temporárias,01,"Agricultura, Pecuária E Serviços Relacionados",A,"Agricultura, Pecuária, Produção Florestal, Pes...",1,1,1,1
3,0111399,Cultivo de outros cereais não especificados an...,01113,Cultivo de cereais,011,Produção de lavouras temporárias,01,"Agricultura, Pecuária E Serviços Relacionados",A,"Agricultura, Pecuária, Produção Florestal, Pes...",1,1,1,1
4,0111302,Cultivo de milho,01113,Cultivo de cereais,011,Produção de lavouras temporárias,01,"Agricultura, Pecuária E Serviços Relacionados",A,"Agricultura, Pecuária, Produção Florestal, Pes...",1,1,1,1

### Consulta Diretorios Municípios

In [ ]:
base_path = '../lake/silver/'

# Ler um parquet
parquet_file = base_path + 'br_bd_diretorios_brasil_municipio.parquet'
df = con.execute(f"SELECT * FROM '{parquet_file}' LIMIT 5").fetchdf()
df.head()

,id_municipio,id_municipio_6,id_municipio_tse,id_municipio_rf,id_municipio_bcb,nome,capital_uf,id_comarca,id_regiao_saude,nome_regiao_saude,...,nome_mesorregiao,id_regiao_metropolitana,nome_regiao_metropolitana,ddd,id_uf,sigla_uf,nome_uf,nome_regiao,amazonia_legal,centroide
0,5101837,510183,<NA>,<NA>,<NA>,Boa Esperança do Norte,<NA>,<NA>,<NA>,NaN,...,NaN,NaN,NaN,<NA>,51,MT,Mato Grosso,Centro-Oeste,1,POINT(-54.9417429754238 -13.463197935201)
1,1100809,110080,477,681,46961,Candeias do Jamari,0,1100205,11004,Madeira-Mamoré,...,Madeira-Guaporé,101,Região Metropolitana de Porto Velho,69,11,RO,Rondônia,Norte,1,POINT(-63.3254198532114 -8.88702392955617)
2,1100338,110033,434,47,44516,Nova Mamoré,0,1100106,11004,Madeira-Mamoré,...,Madeira-Guaporé,NaN,NaN,69,11,RO,Rondônia,Norte,1,POINT(-64.6295025002404 -10.3822863210755)
3,1100205,110020,35,3,30719,Porto Velho,1,1100205,11004,Madeira-Mamoré,...,Madeira-Guaporé,101,Região Metropolitana de Porto Velho,69,11,RO,Rondônia,Norte,1,POINT(-64.3041357999869 -9.15394033687075)
4,1101104,110110,493,683,46851,Itapuã do Oeste,0,1100205,11004,Madeira-Mamoré,...,Madeira-Guaporé,NaN,NaN,69,11,RO,Rondônia,Norte,1,POINT(-63.044960463046 -9.17019402601564)

### Join com descrição da divisão CNAE
Vamos unir a tabela de operações com o diretório de CNAE para trazer a descrição da divisão.

In [ ]:
base_operacoes = '../lake/silver/br_bndes_operacoes.parquet'
base_cnae = '../lake/silver/br_bd_diretorios_brasil_cnae_2.parquet'
base_municipio = '../lake/silver/br_bd_diretorios_brasil_municipio.parquet'

query = f"""
SELECT op.*, cnae.descricao_divisao, mn.sigla_uf, mn.nome_regiao FROM '{base_operacoes}' AS op
LEFT JOIN '{base_cnae}' AS cnae
    ON op.divisao_cnae = cnae.divisao
LEFT JOIN '{base_municipio}' AS mn
    ON op.id_municipio = mn.id_municipio
LIMIT 10
"""

resultado = con.execute(query).fetchdf()
resultado.head()

,razao_social_cliente,cnpj_cliente,descricao_projeto,sigla_uf,nome_municipio,id_municipio,id_contrato,data_contratacao,valor_contratado,valor_desembolsado,...,situacao_contrato,secao_cnae,divisao_cnae,grupo_cnae,classe_cnae,subclasse_cnae,data_apuracao,descricao_divisao,sigla_uf_1,nome_regiao
0,LAR COOPERATIVA AGROINDUSTRIAL,77752293000198,DIRETA - AMPLICACAO DE LINHA DE ABATE DE FRANG...,PR,MATELANDIA,4115606,09203571,2009-06-29,66998000.0,66998000.0,...,LIQUIDADO,C,10,101,10121,1012101,2026-06-04,Fabricação De Produtos Alimentícios,PR,Sul
1,COCARI - COOPERATIVA AGROPECUARIA E INDUSTRIAL,78956968000183,SUPLEMENTACAO DE RECURSOS A IMPLANTACAO DE UM ...,PR,MANDAGUARI,4114203,09204441,2009-06-30,37000000.0,37000000.0,...,LIQUIDADO,C,10,101,10121,1012101,2026-06-04,Fabricação De Produtos Alimentícios,PR,Sul
2,COCARI - COOPERATIVA AGROPECUARIA E INDUSTRIAL,78956968000183,SUPLEMENTACAO DE RECURSOS A IMPLANTACAO DE UM ...,PR,MANDAGUARI,4114203,09204451,2009-10-09,50000000.0,50000000.0,...,LIQUIDADO,C,10,101,10121,1012101,2026-06-04,Fabricação De Produtos Alimentícios,PR,Sul
3,COPACOL-COOPERATIVA AGROINDUSTRIAL CONSOLATA,76093731000190,OPERACAO MISTA DO BNDES E BRDE PARA IMPLANTACA...,PR,CAFELANDIA,4103453,10205201,2010-06-28,15244000.0,15244000.0,...,LIQUIDADO,C,10,101,10121,1012101,2026-06-04,Fabricação De Produtos Alimentícios,PR,Sul
4,COPACOL-COOPERATIVA AGROINDUSTRIAL CONSOLATA,76093731000190,OPERACAO MISTA DO BNDES E BRDE PARA IMPLANTACA...,PR,CAFELANDIA,4103453,10205201,2010-06-28,34548000.0,34548000.0,...,LIQUIDADO,C,10,101,10121,1012101,2026-06-04,Fabricação De Produtos Alimentícios,PR,Sul